### ISSUE TITLE
No longer works with Prettier 3.6.0 and newer

### ISSUE THREAD

**Issue by TSenter** [auvred/prettier-pnp#14]
Starting in [Prettier 3.6.0](https://prettier.io/blog/2025/06/23/3.6.0), the `prettier/internals/cli.mjs` script has been moved to `prettier/internals/legacy-cli.mjs`. Running `prettier-pnp` now fails:

```sh
$ prettier-pnp --pn sql --pn sh --pn java --pnp @prettier/plugin-xml --pnp prettier-plugin-ember-template-tag --write --config "~/.prettierrc.js" --ignore-path "~/.prettierignore"
----- Running prettier -----

node:internal/modules/esm/resolve:283
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/wsl/.local/share/pnpm/global/5/.pnpm/prettier-pnp@0.3.0/node_modules/prettier/internal/cli.mjs' imported from /home/wsl/.local/share/pnpm/global/5/.pnpm/prettier-pnp@0.3.0/node_modules/prettier-pnp/dist/bin.js
    at finalizeResolution (node:internal/modules/esm/resolve:283:11)
    at moduleResolve (node:internal/modules/esm/resolve:952:10)
    at defaultResolve (node:internal/modules/esm/resolve:1188:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:708:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:657:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:640:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:264:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:605:34)
    at defaultImportModuleDynamicallyForModule (node:internal/modules/esm/utils:221:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:260:12) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///home/wsl/.local/share/pnpm/global/5/.pnpm/prettier-pnp@0.3.0/node_modules/prettier/internal/cli.mjs'
}

Node.js v20.19.6
```

It looks like the current version works with Prettier 3.5.3 at the latest.

**Comment by auvred** [comment]
Published `0.4.0`. It should work now
